import React from 'react'

export default function PrivacyPolicySection() {
  return (
    <div>
      <div id="body" className="body">
  <div className="bg-[#fceaea] py-4">
    <div className=" main-container px-3">
      <header className="text-center">
        <h2 className="text-2xl sm:text-3xl font-bold">Privacy Policy</h2>
        <nav className="flex justify-center mt-2 text-sm text-[var(--text)] space-x-2">
          <a href="/" className="hover:underline">Home</a>
          <span>/</span>
          <span>Privacy Policy</span>
        </nav>
      </header>
    </div>
  </div>
  <section className="bg-white py-8">
    <div className="main-container px-2">
      <div className="space-y-6">
        <div className="cms space-y-4 text-[var(--text)]">
          
          <h1 className="text-xl sm:text-2xl font-medium">Privacy Policy for Sorty</h1>
          
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
          <p>Now THEREFORE, in consideration of mutual promises, covenants and conditions set forth herein, The parties hereto agree to the terms mentioned in this agreement/proposal.</p>
          
          <p className="font-bold">Definitions</p>
          <p>For the purposes of this Privacy Policy:</p>
          <p><strong>1. Account:</strong> unique account created for You to access our Service or parts of our Service.</p>
          <p><strong>2. Affiliate:</strong> means an entity that controls, is controlled by or is under common control with a party...</p>
          <p><strong>3. Application:</strong> refers to Yokart, the software program provided by the Company.</p>
          <p><strong>4. Company:</strong> (referred to as "the Company", "We", "Us" or "Our") refers to Ablysoft Pvt Ltd.</p>
          <p><strong>5. Country:</strong> refers to Punjab, India.</p>
          <p><strong>6. Device:</strong> any device that can access the Service such as a computer, cellphone, or tablet.</p>
          <p><strong>7. Personal Data:</strong> any information that relates to an identified or identifiable individual.</p>
          <p><strong>8. Service Provider:</strong> refers to the Application.</p>
          <p><strong>10. Usage Data:</strong> data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</p>
          <p><strong>11. You:</strong> the individual accessing or using the Service, or the company on behalf of which such individual is accessing the Service.</p>
          
          <p className="font-bold">CCPA Privacy Rights (Do Not Sell My Personal Information)</p>
          <ul className="list-decimal list-inside ml-4 space-y-1">
            <li>Request disclosure of categories and pieces of personal data collected.</li>
            <li>Request deletion of any personal data collected.</li>
            <li>Request that a business does not sell the consumer's personal data.</li>
          </ul>
          <p>If you make a request, we have one month to respond. Contact us to exercise these rights.</p>
          
          <p className="font-bold">GDPR Data Protection Rights</p>
          <ul className="list-decimal list-inside ml-4 space-y-1">
            <li>Right to access – request copies of personal data.</li>
            <li>Right to rectification – request corrections to inaccurate/incomplete data.</li>
            <li>Right to erasure – request erasure under certain conditions.</li>
            <li>Right to restrict processing – restrict processing under certain conditions.</li>
            <li>Right to object – object to processing under certain conditions.</li>
            <li>Right to data portability – request transfer of collected data to another organization or directly to you.</li>
          </ul>
          
          <p className="font-bold">Collecting and Using Your Personal Data</p>
          <p className="font-bold">Types of Data Collected</p>
          <p>We may collect personally identifiable information such as:</p>
          <ul className="list-decimal list-inside ml-4 space-y-1">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Usage Data</li>
          </ul>

          <p className="font-bold">Usage Data</p>
          <p>Usage Data is collected automatically when using the Service, including IP address, browser type, pages visited, time spent, device identifiers, etc.</p>

          <p className="font-bold">Information Collected while Using the Application</p>
          <p>We may collect location information with your permission to provide and improve features. Data may be stored on your device or uploaded to servers.</p>

          <p className="font-bold">Use of Your Personal Data</p>
          <ul className="list-decimal list-inside ml-4 space-y-1">
            <li>Provide and maintain our Service</li>
            <li>Manage Your Account</li>
            <li>Contact You</li>
            <li>Provide news, offers, and information</li>
            <li>Manage Your requests</li>
            <li>Other purposes: analysis, trends, improvement</li>
          </ul>

          <p className="font-bold">Retention of Your Personal Data</p>
          <p>We retain personal data only as long as necessary for purposes outlined in this Privacy Policy.</p>

          <p className="font-bold">Transfer of Your Personal Data</p>
          <p>Information may be transferred outside your jurisdiction. We ensure adequate security measures are in place.</p>

          <p className="font-bold">Children's Privacy</p>
          <p>Our Service does not target anyone under 13. We remove data collected from children without parental consent.</p>

          <p className="font-bold">Links to Other Websites</p>
          <p>We are not responsible for third-party websites linked from our Service. Review their Privacy Policies.</p>

          <p className="font-bold">Changes to this Privacy Policy</p>
          <p>We may update this Privacy Policy periodically. Updates are effective when posted on this page.</p>

          <p className="font-bold">Contact Us</p>
          <p>By email: <a href="mailto:sales@fatbit.com" className="text-[#ee3e5a] hover:underline">sales@fatbit.com</a></p>

        </div>
      </div>
    </div>
  </section>
</div>

    </div>
  )
}
